/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Farzan
 */
public class HRManager extends javax.swing.JFrame {

    /**
     * Creates new form HRManager
     */
    public HRManager() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnadddes = new javax.swing.JButton();
        btnviewdes = new javax.swing.JButton();
        btnupdatedes = new javax.swing.JButton();
        btnaddemp = new javax.swing.JButton();
        btnviewemp = new javax.swing.JButton();
        btnupdateemp = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnadddep = new javax.swing.JButton();
        btnviewdep = new javax.swing.JButton();
        btnupdatedep = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HR Manager Interface");
        setMinimumSize(new java.awt.Dimension(850, 800));
        setPreferredSize(new java.awt.Dimension(1100, 900));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Welcome To EMS");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 360, 74));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 204));
        jLabel2.setText("Designation Section");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 550, 250, 40));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 204));
        jLabel4.setText("Employee Section");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 250, 40));

        btnadddes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/1091916.png"))); // NOI18N
        btnadddes.setToolTipText("");
        btnadddes.setPreferredSize(new java.awt.Dimension(100, 20));
        btnadddes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadddesActionPerformed(evt);
            }
        });
        getContentPane().add(btnadddes, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 600, 130, 120));

        btnviewdes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/free-file-icon-1453-thumb.png"))); // NOI18N
        btnviewdes.setToolTipText("");
        btnviewdes.setPreferredSize(new java.awt.Dimension(100, 20));
        btnviewdes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewdesActionPerformed(evt);
            }
        });
        getContentPane().add(btnviewdes, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 600, 130, 120));

        btnupdatedes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/24937-200.png"))); // NOI18N
        btnupdatedes.setToolTipText("");
        btnupdatedes.setPreferredSize(new java.awt.Dimension(100, 20));
        btnupdatedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdatedesActionPerformed(evt);
            }
        });
        getContentPane().add(btnupdatedes, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 600, 130, 120));

        btnaddemp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/pngwing.com (2) (1).png"))); // NOI18N
        btnaddemp.setToolTipText("");
        btnaddemp.setPreferredSize(new java.awt.Dimension(100, 20));
        btnaddemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddempActionPerformed(evt);
            }
        });
        getContentPane().add(btnaddemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 130, 120));

        btnviewemp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/pngwing.com (3) (1).png"))); // NOI18N
        btnviewemp.setToolTipText("");
        btnviewemp.setPreferredSize(new java.awt.Dimension(100, 20));
        btnviewemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewempActionPerformed(evt);
            }
        });
        getContentPane().add(btnviewemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 130, 120));

        btnupdateemp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/employee-update-3194586-2661577-removebg-preview (1).png"))); // NOI18N
        btnupdateemp.setToolTipText("");
        btnupdateemp.setPreferredSize(new java.awt.Dimension(100, 20));
        btnupdateemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateempActionPerformed(evt);
            }
        });
        getContentPane().add(btnupdateemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, 130, 120));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 255, 204));
        jLabel5.setText("Department Section");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 250, 40));

        btnadddep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/2996504-200.png"))); // NOI18N
        btnadddep.setToolTipText("");
        btnadddep.setPreferredSize(new java.awt.Dimension(100, 20));
        btnadddep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadddepActionPerformed(evt);
            }
        });
        getContentPane().add(btnadddep, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 130, 120));

        btnviewdep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/pngwing.com (5) (1).png"))); // NOI18N
        btnviewdep.setToolTipText("");
        btnviewdep.setPreferredSize(new java.awt.Dimension(100, 20));
        btnviewdep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewdepActionPerformed(evt);
            }
        });
        getContentPane().add(btnviewdep, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, 130, 120));

        btnupdatedep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/Untitled_design-removebg-preview.png"))); // NOI18N
        btnupdatedep.setToolTipText("");
        btnupdatedep.setPreferredSize(new java.awt.Dimension(100, 20));
        btnupdatedep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdatedepActionPerformed(evt);
            }
        });
        getContentPane().add(btnupdatedep, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 410, 130, 120));

        btnexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/pngwing.com (1) (1).png"))); // NOI18N
        btnexit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnexit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        getContentPane().add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 770, 40, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/bg.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -10, 1250, 900));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
        Login login = new Login ();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnexitActionPerformed

    private void btnaddempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddempActionPerformed
        // TODO add your handling code here:
        AddEmployee addemp = new AddEmployee();
        addemp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnaddempActionPerformed

    private void btnadddepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadddepActionPerformed
        // TODO add your handling code here:
        AddDepartment dep= new AddDepartment();
        dep.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnadddepActionPerformed

    private void btnadddesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadddesActionPerformed
        // TODO add your handling code here:
        AddDesignation des =new AddDesignation();
        des.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnadddesActionPerformed

    private void btnviewempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewempActionPerformed
        // TODO add your handling code here:
        Viewemp emp =new Viewemp();
        emp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnviewempActionPerformed

    private void btnviewdepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewdepActionPerformed
        // TODO add your handling code here:
        Viewdep dep = new Viewdep();
        dep.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnviewdepActionPerformed

    private void btnviewdesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewdesActionPerformed
        // TODO add your handling code here:
        Viewdes des = new Viewdes();
        des.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnviewdesActionPerformed

    private void btnupdateempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateempActionPerformed
        // TODO add your handling code here:
        UpdateEmployee emp =new UpdateEmployee();
        emp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnupdateempActionPerformed

    private void btnupdatedepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdatedepActionPerformed
        // TODO add your handling code here:
        UpdateDep dep =new UpdateDep();
        dep.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnupdatedepActionPerformed

    private void btnupdatedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdatedesActionPerformed
        // TODO add your handling code here:
        UpdateDes des =new UpdateDes();
        des.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnupdatedesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HRManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HRManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HRManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HRManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HRManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadddep;
    private javax.swing.JButton btnadddes;
    private javax.swing.JButton btnaddemp;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnupdatedep;
    private javax.swing.JButton btnupdatedes;
    private javax.swing.JButton btnupdateemp;
    private javax.swing.JButton btnviewdep;
    private javax.swing.JButton btnviewdes;
    private javax.swing.JButton btnviewemp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
